# Generated by Django 4.2.9 on 2024-02-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_inventario_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='fecha_hora',
            new_name='fecha_prestamo',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='id_tipo',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
